spring.config.import=optional:file:.env[.properties]

cloudinary.url=${CLOUDINARY_URL}

youtube.api.key=${YOUTUBE_API_KEY}

spring.application.name=cms
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.profiles.active=dev
spring.jpa.hibernate.ddl-auto=create-drop
spring.session.jdbc.initialize-schema=always

spring.elasticsearch.uris=${ELASTIC_URL}
logging.level.org.springframework.data.elasticsearch.core.ElasticsearchTemplate=DEBUG

spring.jpa.mapping-resources=hibernate/User.hbm.xml, hibernate/Embed.hbm.xml, hibernate/Testimonial.hbm.xml, hibernate/Category.hbm.xml, hibernate/Tag.hbm.xml

server.servlet.context-path=/api/v1

jwt.secret=${JWT.SECRET}

server.port=${SERVER_PORT}
spring.elasticsearch.rest.compatibility-headers=true